### ISSUE TITLE
Request for improving exclusion configuration in a multi-sources setup

### ISSUE THREAD

**Issue by FredericLeuba** [time2backup/time2backup#166]
We can give several sources of backup, but the exclusion file is unique.
Each exclusion path is related to the source... but which one, when you have several?
that does not work.

I ask for a way to indicate to what backup source each exclusion applies.

**Comment by pruje** [comment]
I forgot to tell you, but there is a solution to your issue:
You can empty the global exclude file and create an exclude file named `.rsyncignore` at the root of each source you want to backup.
This feature needs to be documented.

**Comment by pruje** [comment]
The rsynignore use will be documented in 1.8.0

**Comment by pruje** [comment]
Done in commit 96c1f8d49eb5e2c0bc5d6ca556e3106765593fdd

Read the updated [documentation here](https://github.com/time2backup/time2backup/blob/96c1f8d49eb5e2c0bc5d6ca556e3106765593fdd/docs/user_manual.md#faq)
