### ISSUE TITLE
Duplicated crontab entry

### ISSUE THREAD

**Issue by FredericLeuba** [time2backup/time2backup#167]
When t2b is run from command line, once without giving the -c option, and once giving the -c option with the default configuration folder, then it creates 2 different crontab entries, though they both relate to the same configuration.

```
# time2backup recurrent backups
* * * * *	"/home/user/time2backup/time2backup.sh" -q backup --recurrent
# time2backup recurrent backups
* * * * *	"/home/user/time2backup/time2backup.sh" -q -c "/home/user/.config/time2backup" backup --recurrent
```

I suggest that t2b always give the -c option in the crontab entry, even when running it without -c, with the default configuration

**Comment by pruje** [comment]
Bug fixed in commit a7154a3387c5ff5278a00324309991884f35820b
